FROM node:14 AS builder

# Create app directory
WORKDIR /usr/src/app


# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm set strict-ssl false
RUN npm config set strict-ssl false

RUN npm install --legacy-peer-deps
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY ./src ./src
COPY ./public ./public

# ADD docker/wait-for-it.sh /wait-for-it.sh
# RUN bash -c 'chmod 777 /wait-for-it.sh'

EXPOSE 3000
CMD [ "npm", "run", "start" ]

#Below is code to run the react in production in static server (Nginx).

# RUN npm run build

# FROM nginx:1.16.0-alpine

# COPY --from=builder /usr/src/app/build /usr/share/nginx/html
# RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.disabled
# COPY ./docker/reactnginx.conf /etc/nginx/conf.d/reactnginx.conf

# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]