FROM nginx:1.26-alpine-perl
# COPY ./build /usr/share/nginx/html
RUN mkdir /var/log/nginx_export
RUN chmod 777 /var/log/nginx_export

RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.disabled
COPY ./nodeapp.conf /etc/nginx/conf.d/nodeapp.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]