apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ecom
  name: ecom-node
  labels:
    app: ecom-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodepod
  template:
    metadata:
      labels:
        app: nodepod
    spec:
      containers:
        - name: nodecontainer
          image: node-server-app:1.0
          ports:
            - containerPort: 5000
          # env:
          #   - name: SOLR_SERVICE_HOST
          #     value: solr
          #   - name: MONGO_SERVICE_HOST
          #     value: mongo
          imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  namespace: ecom
  name: node
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: nodepod

