# filebeat.inputs:
  # - type: log
  #   enabled: true
  #   paths:
  #     - "/var/log/server/*.log"

filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
output.logstash:
  hosts: ["logstash:5000"]
