FROM node:18.20.3-alpine3.18

# Add libvips
RUN apk add --upgrade --no-cache vips-dev build-base --repository https://alpine.global.ssl.fastly.net/alpine/v3.10/community/

RUN apk add --no-cache --upgrade bash

ENV NODE_TLS_REJECT_UNAUTHORIZED=0

# Create app directory
WORKDIR /usr/src/app

COPY package*.json ./

RUN npm set strict-ssl false
RUN npm config set strict-ssl false

RUN npm install --legacy-peer-deps

COPY . .

ADD docker/wait-for-it.sh /wait-for-it.sh
RUN bash -c 'chmod 777 /wait-for-it.sh'

EXPOSE 6000
CMD [ "npm", "run", "server" ]